### ISSUE TITLE
Rewrite OpenID Connect certification documentation

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/website#106]

**Comment by nabokihms** [comment]
Let me know if you need any help with this issue. I periodically run OIDC conformance tests and can help with nuances.

**Comment by sagikazarmark** [comment]
Thanks! I managed to run the tests just now based on the "old" config on the current page.

Right now I'm just trying to simplify the docs, but we should definitely talk about next steps at some point. Would be nice to get at least the Basic OP certification.
