### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#122]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via other site's deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by nate-double-u** [comment]
<img width="924" alt="Screenshot 2022-11-22 at 10 07 27 AM" src="https://user-images.githubusercontent.com/4453979/203389434-d0d573e9-097e-4535-a409-6b38a3bcf019.png">

test deploy: https://app.netlify.com/sites/dexidp/deploys/637d103d33534d0af5fac762

I've made the update, but we should ensure that there are folks from the dexidp project that are able to make Netlify changes.

**Comment by sagikazarmark** [comment]
Thanks @nate-double-u !
