### ISSUE TITLE
Deprecation on Google connector: use "domainToAdminEmail" instead of "adminEmail"

### ISSUE THREAD

**Issue by hawkesn** [dexidp/website#150]
Based on this PR: https://github.com/dexidp/dex/pull/2911
This doc needs to be updated: https://github.com/dexidp/website/blob/main/content/docs/connectors/google.md

This error is appearing: 
```
Deprecated: google: use \"domainToAdminEmail.*: email@address.com\" option instead of \"adminEmail: email@address.com\"."
```

**Comment by MrDeerly** [comment]
Fixed in https://github.com/dexidp/website/pull/154
