### ISSUE TITLE
Reorder pages in documentation list

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#17]
Please work with the maintainers to decide on the correct order for pages in these sections.

_Originally posted by @celestehorgan in https://github.com/dexidp/website/pull/8#discussion_r498477500_

**Comment by hackabletype** [comment]
Current order:

<img width="1392" alt="Screen Shot 2020-10-05 at 5 42 04 PM" src="https://user-images.githubusercontent.com/4453979/95146211-c8b37a80-076c-11eb-86fa-3ccb462cc938.png">

**Comment by nate-double-u** [comment]
Do with issue #18
