### ISSUE TITLE
Provide general info on proposals index page

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#20]
Provide general blurb in content/docs/proposals/_index.md file.

**Comment by sagikazarmark** [comment]
I'm not entirely sure that we want these proposals in the documentation. They aren't documentation pages, rather some rough ideas for features that made it into the repo instead of an issue.

**Comment by hackabletype** [comment]
I'm happy to take it out. I expect this sort of thing is easier to discuss in the newsgroups than here.

**Comment by sagikazarmark** [comment]
Yeah. Can we make them hidden for now. We can decide their fate later.

**Comment by hackabletype** [comment]
I can make them draft so they don't show up in the build -- not sure about hiding the source here though.

**Comment by sagikazarmark** [comment]
I meant hide from the website/don't build it. Draft is perfectly fine.
