### ISSUE TITLE
Home Page Content Updates

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#21]
* The content you migrated into the site's index will likely need to be moved into a Getting Started page in the docs proper in future.  We tend to reserve the index pages for marketing purposes on these sites.

_Originally posted by @celestehorgan in https://github.com/dexidp/website/pull/8#issuecomment-703822774_

**Comment by hackabletype** [comment]
When we do this update, we should change how we reference CoreOS as per issue https://github.com/dexidp/website/issues/22, item 2.

**Comment by nate-double-u** [comment]
related to issue https://github.com/dexidp/website/issues/55
