### ISSUE TITLE
Writing apps that use Dex Link broken

### ISSUE THREAD

**Issue by ashu8912** [dexidp/website#25]
This link is broken both in the dex readme and as well as dex website

**Comment by nate-double-u** [comment]
dexidp.io website:
![Screen Shot 2020-10-13 at 3 15 45 PM](https://user-images.githubusercontent.com/4453979/95921901-af7c8080-0da1-11eb-9f79-83453401cd6a.png)
* This should link to https://dexidp.io/docs/using-dex/

**Comment by nate-double-u** [comment]
![Screen Shot 2020-10-13 at 3 20 52 PM](https://user-images.githubusercontent.com/4453979/95922258-67119280-0da2-11eb-8ff6-6ff5c6ef01db.png)
