### ISSUE TITLE
Update or Remove Twitter Button

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#33]
Twitter button currently not linked to anything.

@justaugustus @sagikazarmark is there a twitter account for this project?

![Screen Shot 2020-10-15 at 2 05 40 PM](https://user-images.githubusercontent.com/4453979/96185968-46744480-0f2a-11eb-89d6-536ab7c203ba.png)

**Comment by justaugustus** [comment]
Yep, yep! https://twitter.com/dexidp
