### ISSUE TITLE
Copy edit Dex v2 page, §More storage backends

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#49]
https://dexidp.io/docs/v2/#more-storage-backends

![Screen Shot 2020-10-21 at 11 32 59 AM](https://user-images.githubusercontent.com/4453979/96767803-8b85f400-13cc-11eb-94e4-bd975f6911d1.png)

**Comment by nabokihms** [comment]
Cannot see it now so the issue is probably fixed.
![image](https://github.com/dexidp/website/assets/32434187/9e7c7a98-d232-46fc-910e-f7cc6c1ab625)
