### ISSUE TITLE
Copy edit Dex v2 page, §Rethinking registration

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#50]
https://dexidp.io/docs/v2/#rethinking-registration

![Screen Shot 2020-10-21 at 11 41 13 AM](https://user-images.githubusercontent.com/4453979/96768241-2b438200-13cd-11eb-99e8-5e7f14ccecc3.png)

**Comment by nabokihms** [comment]
Cannot see it now so the issue is probably fixed
![image](https://github.com/dexidp/website/assets/32434187/2c623bb1-179e-4519-ac70-1e00ffff7f71)
