### ISSUE TITLE
Copy edit Authentication Through Gitlab page, §Overview

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#53]
https://dexidp.io/docs/connectors/gitlab/#overview

![Screen Shot 2020-10-21 at 11 52 25 AM](https://user-images.githubusercontent.com/4453979/96769517-c426cd00-13ce-11eb-88cb-878547344b76.png)

**Comment by nabokihms** [comment]
I cannot see it now, so the issue is probably fixed
![image](https://github.com/dexidp/website/assets/32434187/7ddf6cd5-9177-414c-bd59-beb1e2939672)

**Comment by nabokihms** [comment]
Cannot see it now so the issue is probably fixed.
![image](https://github.com/dexidp/website/assets/32434187/9e7c7a98-d232-46fc-910e-f7cc6c1ab625)
