### ISSUE TITLE
Break Navigation Overview Section into smaller parts

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#62]
> I think it's fine for now, although we should probably break the Overview section into smaller parts. For example: Become a maintainer and Running Integration Tests are Dex development related topics.

_Originally posted by @sagikazarmark in https://github.com/dexidp/website/pull/59#issuecomment-716044707_

![Screen Shot 2020-10-24 at 12 06 42 PM](https://user-images.githubusercontent.com/4453979/97091569-3fd18580-162c-11eb-9f4d-f6c635c6528d.png)

**Comment by nabokihms** [comment]
This is fixed after migrating to docsy.
![image](https://github.com/dexidp/website/assets/32434187/5c397857-3eab-4700-a9e9-236352329bc1)
