### ISSUE TITLE
Leftside documention panel too wide

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#63]
As per a feedback from @sagikazarmark, the Documentation panel on the left side may be too wide.

Possible solutions:
* CSS update to narrow it (being mindful of how long titles wrap)
* Shorten `linkTitle` in the markdown headers to see if that solves the problem

<img width="1552" alt="Screen Shot 2020-10-28 at 11 46 32 AM" src="https://user-images.githubusercontent.com/4453979/97482558-36a72800-194e-11eb-9755-6df8335e1542.png">

**Comment by nabokihms** [comment]
This is fixed after migrating to docsy.
