### ISSUE TITLE
Edit on GitHub button misplaced

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#64]
The `Edit on GitHub` button on documentation pages should be aligned fully to the right of it's column, but is floating much further left. Please see the screen shot provided. This is occurring throughout.

<img width="1552" alt="Screen Shot 2020-10-28 at 11 49 35 AM" src="https://user-images.githubusercontent.com/4453979/97482802-884fb280-194e-11eb-8578-e45b8d4fa83d.png">

**Comment by nabokihms** [comment]
This is fixed after migrating to docsy.
