### ISSUE TITLE
Responsive elements produce odd results at some viewport sizes

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#65]
Note the copyright footer, it matches with the nav bar and jumbo tron, so looks odd at some viewport sizes.

<img width="1552" alt="Screen Shot 2020-10-28 at 12 06 22 PM" src="https://user-images.githubusercontent.com/4453979/97484610-d796e280-1950-11eb-962b-ed4dd715aaba.png">

<img width="832" alt="Screen Shot 2020-10-28 at 12 06 35 PM" src="https://user-images.githubusercontent.com/4453979/97484619-db2a6980-1950-11eb-9b4b-ea29d971730c.png">

**Comment by nate-double-u** [comment]
I'm not sure if we should rewrite the footer to move over with the content, or if there is something else is going on.

**Comment by nabokihms** [comment]
It should be fixed after migrating to docsy. (I believe so).
