### ISSUE TITLE
Update Contributing page

### ISSUE THREAD

**Issue by nate-double-u** [dexidp/website#68]
With @srenatus [leaving the maintainer list](https://github.com/dexidp/dex/pull/1880), I think the https://dexidp.io/docs/contributing/ page potentially becomes out of date.

- [ ] Review people referenced, update as needed
- [ ] Update contacts from raw Github @-mentions to links (or links to email addresses)

**Comment by sagikazarmark** [comment]
@nate-double-u took care of it for you ;)

Updated a few other things on the page as well, so feel free to check it for errors. Thanks!

**Comment by nate-double-u** [comment]
> @nate-double-u took care of it for you ;)

Thanks! 😃️
I'll look at the PR now!
