### ISSUE TITLE
Spacing in social buttons

### ISSUE THREAD

**Issue by sagikazarmark** [dexidp/website#70]
Feels like there should be some space between the icons and the text.

![Screenshot 2020-12-09 at 16 12 26](https://user-images.githubusercontent.com/1226384/101647707-56476b00-3a39-11eb-9573-8b5cee2c0db2.png)

**Comment by nate-double-u** [comment]
I noticed that on one of the other sites I worked on too. 
Simple fix by adding a non breaking space in `layouts/partials/social-buttons.html`: https://github.com/containernetworking/cni.dev/pull/49/files
