### ISSUE TITLE
Keystone connector documentation

### ISSUE THREAD

**Issue by nabokihms** [dexidp/website#89]
In dex [v2.14.0](https://github.com/dexidp/dex/releases/tag/v2.14.0), keystone connector was added. 
It still works, and it even has integration tests, but sadly, the keystone connector has no documentation.

**Comment by nate-double-u** [comment]
We may want to add something to the PR Template that nudges contributors to remember the docs when creating new PRs.
(https://github.com/dexidp/dex/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by nabokihms** [comment]
Good idea. It could be presented as a set of some checkboxes, like:
- [] DCO has been signed
- [] Unit tests have been added, if necessary.
- [] Integration tests have been added, if necessary.
- [] PR with documentation changes has been opened, if necessary.
...
And so on.
